// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-ent-project/internal/ent/car"
	"go-ent-project/internal/ent/policestation"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Car is the model entity for the Car schema.
type Car struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Make holds the value of the "make" field.
	Make string `json:"make,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Year holds the value of the "year" field.
	Year int `json:"year,omitempty"`
	// Registration holds the value of the "registration" field.
	Registration string `json:"registration,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// PoliceStationID holds the value of the "police_station_id" field.
	PoliceStationID *uuid.UUID `json:"police_station_id,omitempty"`
	// StolenDate holds the value of the "stolen_date" field.
	StolenDate time.Time `json:"stolen_date,omitempty"`
	// FirNumber holds the value of the "fir_number" field.
	FirNumber string `json:"fir_number,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CarQuery when eager-loading is set.
	Edges        CarEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CarEdges holds the relations/edges for other nodes in the graph.
type CarEdges struct {
	// PoliceStation holds the value of the police_station edge.
	PoliceStation *PoliceStation `json:"police_station,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// PoliceStationOrErr returns the PoliceStation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CarEdges) PoliceStationOrErr() (*PoliceStation, error) {
	if e.PoliceStation != nil {
		return e.PoliceStation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: policestation.Label}
	}
	return nil, &NotLoadedError{edge: "police_station"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Car) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case car.FieldPoliceStationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case car.FieldYear:
			values[i] = new(sql.NullInt64)
		case car.FieldMake, car.FieldModel, car.FieldRegistration, car.FieldColor, car.FieldFirNumber:
			values[i] = new(sql.NullString)
		case car.FieldCreatedAt, car.FieldUpdatedAt, car.FieldStolenDate:
			values[i] = new(sql.NullTime)
		case car.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Car fields.
func (c *Car) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case car.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				c.ID = *value
			}
		case car.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				c.CreatedAt = value.Time
			}
		case car.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				c.UpdatedAt = value.Time
			}
		case car.FieldMake:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field make", values[i])
			} else if value.Valid {
				c.Make = value.String
			}
		case car.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				c.Model = value.String
			}
		case car.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				c.Year = int(value.Int64)
			}
		case car.FieldRegistration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registration", values[i])
			} else if value.Valid {
				c.Registration = value.String
			}
		case car.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				c.Color = value.String
			}
		case car.FieldPoliceStationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field police_station_id", values[i])
			} else if value.Valid {
				c.PoliceStationID = new(uuid.UUID)
				*c.PoliceStationID = *value.S.(*uuid.UUID)
			}
		case car.FieldStolenDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field stolen_date", values[i])
			} else if value.Valid {
				c.StolenDate = value.Time
			}
		case car.FieldFirNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fir_number", values[i])
			} else if value.Valid {
				c.FirNumber = value.String
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Car.
// This includes values selected through modifiers, order, etc.
func (c *Car) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryPoliceStation queries the "police_station" edge of the Car entity.
func (c *Car) QueryPoliceStation() *PoliceStationQuery {
	return NewCarClient(c.config).QueryPoliceStation(c)
}

// Update returns a builder for updating this Car.
// Note that you need to call Car.Unwrap() before calling this method if this Car
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Car) Update() *CarUpdateOne {
	return NewCarClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Car entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Car) Unwrap() *Car {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Car is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Car) String() string {
	var builder strings.Builder
	builder.WriteString("Car(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("created_at=")
	builder.WriteString(c.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(c.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("make=")
	builder.WriteString(c.Make)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(c.Model)
	builder.WriteString(", ")
	builder.WriteString("year=")
	builder.WriteString(fmt.Sprintf("%v", c.Year))
	builder.WriteString(", ")
	builder.WriteString("registration=")
	builder.WriteString(c.Registration)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(c.Color)
	builder.WriteString(", ")
	if v := c.PoliceStationID; v != nil {
		builder.WriteString("police_station_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("stolen_date=")
	builder.WriteString(c.StolenDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("fir_number=")
	builder.WriteString(c.FirNumber)
	builder.WriteByte(')')
	return builder.String()
}

// Cars is a parsable slice of Car.
type Cars []*Car
