// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (c *Camera) PoliceStation(ctx context.Context) (*PoliceStation, error) {
	result, err := c.Edges.PoliceStationOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryPoliceStation().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (c *Car) PoliceStation(ctx context.Context) (*PoliceStation, error) {
	result, err := c.Edges.PoliceStationOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryPoliceStation().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (ps *PoliceStation) Users(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = ps.NamedUsers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = ps.Edges.UsersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = ps.QueryUsers().All(ctx)
	}
	return result, err
}

func (ps *PoliceStation) Camera(ctx context.Context) (result []*Camera, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = ps.NamedCamera(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = ps.Edges.CameraOrErr()
	}
	if IsNotLoaded(err) {
		result, err = ps.QueryCamera().All(ctx)
	}
	return result, err
}

func (ps *PoliceStation) Car(ctx context.Context) (result []*Car, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = ps.NamedCar(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = ps.Edges.CarOrErr()
	}
	if IsNotLoaded(err) {
		result, err = ps.QueryCar().All(ctx)
	}
	return result, err
}

func (ps *PoliceStation) Parent(ctx context.Context) (*PoliceStation, error) {
	result, err := ps.Edges.ParentOrErr()
	if IsNotLoaded(err) {
		result, err = ps.QueryParent().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (ps *PoliceStation) ChildStations(ctx context.Context) (result []*PoliceStation, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = ps.NamedChildStations(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = ps.Edges.ChildStationsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = ps.QueryChildStations().All(ctx)
	}
	return result, err
}

func (r *Role) Permissions(ctx context.Context) (result []*Permission, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = r.NamedPermissions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = r.Edges.PermissionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = r.QueryPermissions().All(ctx)
	}
	return result, err
}

func (r *Role) Users(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = r.NamedUsers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = r.Edges.UsersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = r.QueryUsers().All(ctx)
	}
	return result, err
}

func (u *User) Role(ctx context.Context) (*Role, error) {
	result, err := u.Edges.RoleOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryRole().Only(ctx)
	}
	return result, err
}

func (u *User) PoliceStation(ctx context.Context) (*PoliceStation, error) {
	result, err := u.Edges.PoliceStationOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryPoliceStation().Only(ctx)
	}
	return result, MaskNotFound(err)
}
