// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Camera is the predicate function for camera builders.
type Camera func(*sql.Selector)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// PoliceStation is the predicate function for policestation builders.
type PoliceStation func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
