package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"go-ent-project/internal/ent"

	"entgo.io/contrib/entgql"
)

// Edges is the resolver for the edges field.
func (r *cameraConnectionResolver) Edges(ctx context.Context, obj *ent.CameraConnection) ([]*ent.Camera, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}

// Edges is the resolver for the edges field.
func (r *policeStationConnectionResolver) Edges(ctx context.Context, obj *ent.PoliceStationConnection) ([]*ent.PoliceStation, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context, where *ent.UserWhereInput, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.UserOrder) (*ent.UserConnection, error) {
	paginate, _ := r.Client.User.Query().Paginate(ctx, after, first, before, last, ent.WithUserFilter(where.Filter), ent.WithUserOrder(orderBy))

	return paginate, nil
}

// GetPoliceStations is the resolver for the getPoliceStations field.
func (r *queryResolver) GetPoliceStations(ctx context.Context, where *ent.PoliceStationWhereInput, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.PoliceStationOrder) (*ent.PoliceStationConnection, error) {
	paginate, _ := r.Client.PoliceStation.Query().Paginate(ctx, after, first, before, last, ent.WithPoliceStationFilter(where.Filter), ent.WithPoliceStationOrder(orderBy))

	return paginate, nil
}

// GetCameras is the resolver for the getCameras field.
func (r *queryResolver) GetCameras(ctx context.Context, where *ent.CameraWhereInput, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.CameraOrder) (*ent.CameraConnection, error) {
	panic(fmt.Errorf("not implemented: GetCameras - getCameras"))
}

// Edges is the resolver for the edges field.
func (r *userConnectionResolver) Edges(ctx context.Context, obj *ent.UserConnection) ([]*ent.User, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}

// CameraConnection returns CameraConnectionResolver implementation.
func (r *Resolver) CameraConnection() CameraConnectionResolver { return &cameraConnectionResolver{r} }

// PoliceStationConnection returns PoliceStationConnectionResolver implementation.
func (r *Resolver) PoliceStationConnection() PoliceStationConnectionResolver {
	return &policeStationConnectionResolver{r}
}

// UserConnection returns UserConnectionResolver implementation.
func (r *Resolver) UserConnection() UserConnectionResolver { return &userConnectionResolver{r} }

type cameraConnectionResolver struct{ *Resolver }
type policeStationConnectionResolver struct{ *Resolver }
type userConnectionResolver struct{ *Resolver }
