package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"go-ent-project/graph/model"
	"go-ent-project/internal/ent"
	"go-ent-project/internal/ent/camera"
	"go-ent-project/internal/ent/event"
	"sort"
	"time"
)

// PoliceStationCameraCounts is the resolver for the policeStationCameraCounts field.
func (r *queryResolver) PoliceStationCameraCounts(ctx context.Context) ([]*model.PoliceStationCameraCount, error) {
	psList, err := r.Client.PoliceStation.Query().WithCamera().All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch police stations: %w", err)
	}

	var result []*model.PoliceStationCameraCount
	for _, ps := range psList {
		result = append(result, &model.PoliceStationCameraCount{
			PoliceStationName: ps.Name,
			CameraCount:       len(ps.Edges.Camera),
		})
	}
	return result, nil
}

// PoliceStationCameraStatusCounts is the resolver for the policeStationCameraStatusCounts field.
func (r *queryResolver) PoliceStationCameraStatusCounts(ctx context.Context) ([]*model.PoliceStationCameraStatusCount, error) {
	psList, err := r.Client.PoliceStation.Query().WithCamera().All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch police stations: %w", err)
	}

	var result []*model.PoliceStationCameraStatusCount
	for _, ps := range psList {
		working := 0
		nonWorking := 0
		for _, cam := range ps.Edges.Camera {
			if cam.LastPing.After(time.Now().Add(-time.Hour * 1)) {
				working++
			} else {
				nonWorking++
			}
		}
		result = append(result, &model.PoliceStationCameraStatusCount{
			PoliceStationName:     ps.Name,
			WorkingCameraCount:    working,
			NonWorkingCameraCount: nonWorking,
		})
	}
	return result, nil
}

// VehicleTrackingStats is the resolver for the vehicleTrackingStats field.
func (r *queryResolver) VehicleTrackingStats(ctx context.Context) ([]*model.VehicleTrackingStat, error) {
	type result struct {
		CreatedAt    time.Time `json:"created_at"`
		VehicleCount int       `json:"count"`
	}

	startOfMonth := time.Date(time.Now().Year(), time.Now().Month(), 1, 0, 0, 0, 0, time.UTC)
	startOfNextMonth := startOfMonth.AddDate(0, 1, 0)

	var rows []result
	err := r.Client.Event.
		Query().Where(
		event.CreatedAtGTE(startOfMonth),    // created_at >= start of this month
		event.CreatedAtLT(startOfNextMonth), // created_at < start of next month
	).GroupBy(event.FieldCreatedAt).
		Aggregate(ent.Count()).
		Scan(ctx, &rows)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch vehicle stats: %w", err)
	}

	dateCount := make(map[string]int)

	for _, row := range rows {
		date := row.CreatedAt.Format("2006-01-02") // Only date part
		dateCount[date]++
	}

	// Prepare the final output
	var output []*model.VehicleTrackingStat
	for date, count := range dateCount {
		output = append(output, &model.VehicleTrackingStat{
			Date:         date,
			VehicleCount: count,
		})
	}

	// Optionally, sort by date
	sort.Slice(output, func(i, j int) bool {
		return output[i].Date < output[j].Date
	})

	return output, nil
}

// DashboardStats is the resolver for the dashboardStats field.
func (r *queryResolver) DashboardStats(ctx context.Context) (*model.DashboardStats, error) {
	// Count users
	totalUsers, err := r.Client.User.Query().Count(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to count users: %w", err)
	}

	// Count all cameras
	totalCameras, err := r.Client.Camera.Query().Count(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to count cameras: %w", err)
	}

	// Count working cameras
	workingCameras, err := r.Client.Camera.Query().Where(
		camera.LastPingGTE(time.Now().Add(-time.Hour * 1)), // Last ping within the last 1 day
	).Count(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to count working cameras: %w", err)
	}

	return &model.DashboardStats{
		TotalUsers:     totalUsers,
		TotalCameras:   totalCameras,
		WorkingCameras: workingCameras,
	}, nil
}
