// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"go-ent-project/internal/ent"

	"entgo.io/contrib/entgql"
	"github.com/google/uuid"
)

type CameraEventStat struct {
	CameraID   string `json:"cameraID"`
	EventCount int    `json:"eventCount"`
}

type CustomEvent struct {
	Camera *ent.Camera `json:"camera,omitempty"`
	Event  *ent.Event  `json:"event,omitempty"`
}

type DashboardStats struct {
	TotalUsers        int `json:"totalUsers"`
	TotalCameras      int `json:"totalCameras"`
	WorkingCameras    int `json:"workingCameras"`
	NonWorkingCameras int `json:"nonWorkingCameras"`
}

type DistrictVehicleCount struct {
	District     string `json:"district"`
	VehicleCount int    `json:"vehicleCount"`
}

type EventHourStat struct {
	Hour       string `json:"hour"`
	EventCount int    `json:"eventCount"`
}

type EventList struct {
	PageInfo *entgql.PageInfo[uuid.UUID] `json:"pageInfo"`
	Node     []*CustomEvent              `json:"node"`
}

type Location struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type PoliceStationCameraCount struct {
	PoliceStationName string `json:"policeStationName"`
	CameraCount       int    `json:"cameraCount"`
}

type PoliceStationCameraStatusCount struct {
	PoliceStationName     string `json:"policeStationName"`
	WorkingCameraCount    int    `json:"workingCameraCount"`
	NonWorkingCameraCount int    `json:"nonWorkingCameraCount"`
}

type PoliceStationVehicleCount struct {
	PoliceStationName string `json:"policeStationName"`
	VehicleCount      int    `json:"vehicleCount"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type VehicleTrackingStat struct {
	Date         string `json:"date"`
	VehicleCount int    `json:"vehicleCount"`
}
