// Code generated by ent, DO NOT EDIT.

package vehicledata

import (
	"go-ent-project/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlateChannel applies equality check predicate on the "plate_channel" field. It's identical to PlateChannelEQ.
func PlateChannel(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateChannel, v))
}

// PlateIsExist applies equality check predicate on the "plate_is_exist" field. It's identical to PlateIsExistEQ.
func PlateIsExist(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateIsExist, v))
}

// PlateColor applies equality check predicate on the "plate_color" field. It's identical to PlateColorEQ.
func PlateColor(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateColor, v))
}

// PlateNumber applies equality check predicate on the "plate_number" field. It's identical to PlateNumberEQ.
func PlateNumber(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateNumber, v))
}

// PlateType applies equality check predicate on the "plate_type" field. It's identical to PlateTypeEQ.
func PlateType(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateType, v))
}

// PlateRegion applies equality check predicate on the "plate_region" field. It's identical to PlateRegionEQ.
func PlateRegion(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateRegion, v))
}

// PlateUploadNum applies equality check predicate on the "plate_upload_num" field. It's identical to PlateUploadNumEQ.
func PlateUploadNum(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateUploadNum, v))
}

// SnapAllowUser applies equality check predicate on the "snap_allow_user" field. It's identical to SnapAllowUserEQ.
func SnapAllowUser(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapAllowUser, v))
}

// SnapAllowUserEndTime applies equality check predicate on the "snap_allow_user_end_time" field. It's identical to SnapAllowUserEndTimeEQ.
func SnapAllowUserEndTime(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapAllowUserEndTime, v))
}

// SnapDefenceCode applies equality check predicate on the "snap_defence_code" field. It's identical to SnapDefenceCodeEQ.
func SnapDefenceCode(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapDefenceCode, v))
}

// SnapDeviceID applies equality check predicate on the "snap_device_id" field. It's identical to SnapDeviceIDEQ.
func SnapDeviceID(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapDeviceID, v))
}

// SnapInCarPeopleNum applies equality check predicate on the "snap_in_car_people_num" field. It's identical to SnapInCarPeopleNumEQ.
func SnapInCarPeopleNum(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapInCarPeopleNum, v))
}

// SnapLanNo applies equality check predicate on the "snap_lan_no" field. It's identical to SnapLanNoEQ.
func SnapLanNo(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapLanNo, v))
}

// SnapOpenStrobe applies equality check predicate on the "snap_open_strobe" field. It's identical to SnapOpenStrobeEQ.
func SnapOpenStrobe(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapOpenStrobe, v))
}

// VehicleSeries applies equality check predicate on the "vehicle_series" field. It's identical to VehicleSeriesEQ.
func VehicleSeries(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldVehicleSeries, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldUpdatedAt, v))
}

// PlateBoundingBoxIsNil applies the IsNil predicate on the "plate_bounding_box" field.
func PlateBoundingBoxIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateBoundingBox))
}

// PlateBoundingBoxNotNil applies the NotNil predicate on the "plate_bounding_box" field.
func PlateBoundingBoxNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateBoundingBox))
}

// PlateChannelEQ applies the EQ predicate on the "plate_channel" field.
func PlateChannelEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateChannel, v))
}

// PlateChannelNEQ applies the NEQ predicate on the "plate_channel" field.
func PlateChannelNEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldPlateChannel, v))
}

// PlateChannelIn applies the In predicate on the "plate_channel" field.
func PlateChannelIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldPlateChannel, vs...))
}

// PlateChannelNotIn applies the NotIn predicate on the "plate_channel" field.
func PlateChannelNotIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldPlateChannel, vs...))
}

// PlateChannelGT applies the GT predicate on the "plate_channel" field.
func PlateChannelGT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldPlateChannel, v))
}

// PlateChannelGTE applies the GTE predicate on the "plate_channel" field.
func PlateChannelGTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldPlateChannel, v))
}

// PlateChannelLT applies the LT predicate on the "plate_channel" field.
func PlateChannelLT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldPlateChannel, v))
}

// PlateChannelLTE applies the LTE predicate on the "plate_channel" field.
func PlateChannelLTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldPlateChannel, v))
}

// PlateChannelIsNil applies the IsNil predicate on the "plate_channel" field.
func PlateChannelIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateChannel))
}

// PlateChannelNotNil applies the NotNil predicate on the "plate_channel" field.
func PlateChannelNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateChannel))
}

// PlateIsExistEQ applies the EQ predicate on the "plate_is_exist" field.
func PlateIsExistEQ(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateIsExist, v))
}

// PlateIsExistNEQ applies the NEQ predicate on the "plate_is_exist" field.
func PlateIsExistNEQ(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldPlateIsExist, v))
}

// PlateIsExistIsNil applies the IsNil predicate on the "plate_is_exist" field.
func PlateIsExistIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateIsExist))
}

// PlateIsExistNotNil applies the NotNil predicate on the "plate_is_exist" field.
func PlateIsExistNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateIsExist))
}

// PlateColorEQ applies the EQ predicate on the "plate_color" field.
func PlateColorEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateColor, v))
}

// PlateColorNEQ applies the NEQ predicate on the "plate_color" field.
func PlateColorNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldPlateColor, v))
}

// PlateColorIn applies the In predicate on the "plate_color" field.
func PlateColorIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldPlateColor, vs...))
}

// PlateColorNotIn applies the NotIn predicate on the "plate_color" field.
func PlateColorNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldPlateColor, vs...))
}

// PlateColorGT applies the GT predicate on the "plate_color" field.
func PlateColorGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldPlateColor, v))
}

// PlateColorGTE applies the GTE predicate on the "plate_color" field.
func PlateColorGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldPlateColor, v))
}

// PlateColorLT applies the LT predicate on the "plate_color" field.
func PlateColorLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldPlateColor, v))
}

// PlateColorLTE applies the LTE predicate on the "plate_color" field.
func PlateColorLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldPlateColor, v))
}

// PlateColorContains applies the Contains predicate on the "plate_color" field.
func PlateColorContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldPlateColor, v))
}

// PlateColorHasPrefix applies the HasPrefix predicate on the "plate_color" field.
func PlateColorHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldPlateColor, v))
}

// PlateColorHasSuffix applies the HasSuffix predicate on the "plate_color" field.
func PlateColorHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldPlateColor, v))
}

// PlateColorIsNil applies the IsNil predicate on the "plate_color" field.
func PlateColorIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateColor))
}

// PlateColorNotNil applies the NotNil predicate on the "plate_color" field.
func PlateColorNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateColor))
}

// PlateColorEqualFold applies the EqualFold predicate on the "plate_color" field.
func PlateColorEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldPlateColor, v))
}

// PlateColorContainsFold applies the ContainsFold predicate on the "plate_color" field.
func PlateColorContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldPlateColor, v))
}

// PlateNumberEQ applies the EQ predicate on the "plate_number" field.
func PlateNumberEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateNumber, v))
}

// PlateNumberNEQ applies the NEQ predicate on the "plate_number" field.
func PlateNumberNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldPlateNumber, v))
}

// PlateNumberIn applies the In predicate on the "plate_number" field.
func PlateNumberIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldPlateNumber, vs...))
}

// PlateNumberNotIn applies the NotIn predicate on the "plate_number" field.
func PlateNumberNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldPlateNumber, vs...))
}

// PlateNumberGT applies the GT predicate on the "plate_number" field.
func PlateNumberGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldPlateNumber, v))
}

// PlateNumberGTE applies the GTE predicate on the "plate_number" field.
func PlateNumberGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldPlateNumber, v))
}

// PlateNumberLT applies the LT predicate on the "plate_number" field.
func PlateNumberLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldPlateNumber, v))
}

// PlateNumberLTE applies the LTE predicate on the "plate_number" field.
func PlateNumberLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldPlateNumber, v))
}

// PlateNumberContains applies the Contains predicate on the "plate_number" field.
func PlateNumberContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldPlateNumber, v))
}

// PlateNumberHasPrefix applies the HasPrefix predicate on the "plate_number" field.
func PlateNumberHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldPlateNumber, v))
}

// PlateNumberHasSuffix applies the HasSuffix predicate on the "plate_number" field.
func PlateNumberHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldPlateNumber, v))
}

// PlateNumberIsNil applies the IsNil predicate on the "plate_number" field.
func PlateNumberIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateNumber))
}

// PlateNumberNotNil applies the NotNil predicate on the "plate_number" field.
func PlateNumberNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateNumber))
}

// PlateNumberEqualFold applies the EqualFold predicate on the "plate_number" field.
func PlateNumberEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldPlateNumber, v))
}

// PlateNumberContainsFold applies the ContainsFold predicate on the "plate_number" field.
func PlateNumberContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldPlateNumber, v))
}

// PlateTypeEQ applies the EQ predicate on the "plate_type" field.
func PlateTypeEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateType, v))
}

// PlateTypeNEQ applies the NEQ predicate on the "plate_type" field.
func PlateTypeNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldPlateType, v))
}

// PlateTypeIn applies the In predicate on the "plate_type" field.
func PlateTypeIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldPlateType, vs...))
}

// PlateTypeNotIn applies the NotIn predicate on the "plate_type" field.
func PlateTypeNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldPlateType, vs...))
}

// PlateTypeGT applies the GT predicate on the "plate_type" field.
func PlateTypeGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldPlateType, v))
}

// PlateTypeGTE applies the GTE predicate on the "plate_type" field.
func PlateTypeGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldPlateType, v))
}

// PlateTypeLT applies the LT predicate on the "plate_type" field.
func PlateTypeLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldPlateType, v))
}

// PlateTypeLTE applies the LTE predicate on the "plate_type" field.
func PlateTypeLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldPlateType, v))
}

// PlateTypeContains applies the Contains predicate on the "plate_type" field.
func PlateTypeContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldPlateType, v))
}

// PlateTypeHasPrefix applies the HasPrefix predicate on the "plate_type" field.
func PlateTypeHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldPlateType, v))
}

// PlateTypeHasSuffix applies the HasSuffix predicate on the "plate_type" field.
func PlateTypeHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldPlateType, v))
}

// PlateTypeIsNil applies the IsNil predicate on the "plate_type" field.
func PlateTypeIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateType))
}

// PlateTypeNotNil applies the NotNil predicate on the "plate_type" field.
func PlateTypeNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateType))
}

// PlateTypeEqualFold applies the EqualFold predicate on the "plate_type" field.
func PlateTypeEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldPlateType, v))
}

// PlateTypeContainsFold applies the ContainsFold predicate on the "plate_type" field.
func PlateTypeContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldPlateType, v))
}

// PlateRegionEQ applies the EQ predicate on the "plate_region" field.
func PlateRegionEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateRegion, v))
}

// PlateRegionNEQ applies the NEQ predicate on the "plate_region" field.
func PlateRegionNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldPlateRegion, v))
}

// PlateRegionIn applies the In predicate on the "plate_region" field.
func PlateRegionIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldPlateRegion, vs...))
}

// PlateRegionNotIn applies the NotIn predicate on the "plate_region" field.
func PlateRegionNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldPlateRegion, vs...))
}

// PlateRegionGT applies the GT predicate on the "plate_region" field.
func PlateRegionGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldPlateRegion, v))
}

// PlateRegionGTE applies the GTE predicate on the "plate_region" field.
func PlateRegionGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldPlateRegion, v))
}

// PlateRegionLT applies the LT predicate on the "plate_region" field.
func PlateRegionLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldPlateRegion, v))
}

// PlateRegionLTE applies the LTE predicate on the "plate_region" field.
func PlateRegionLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldPlateRegion, v))
}

// PlateRegionContains applies the Contains predicate on the "plate_region" field.
func PlateRegionContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldPlateRegion, v))
}

// PlateRegionHasPrefix applies the HasPrefix predicate on the "plate_region" field.
func PlateRegionHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldPlateRegion, v))
}

// PlateRegionHasSuffix applies the HasSuffix predicate on the "plate_region" field.
func PlateRegionHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldPlateRegion, v))
}

// PlateRegionIsNil applies the IsNil predicate on the "plate_region" field.
func PlateRegionIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateRegion))
}

// PlateRegionNotNil applies the NotNil predicate on the "plate_region" field.
func PlateRegionNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateRegion))
}

// PlateRegionEqualFold applies the EqualFold predicate on the "plate_region" field.
func PlateRegionEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldPlateRegion, v))
}

// PlateRegionContainsFold applies the ContainsFold predicate on the "plate_region" field.
func PlateRegionContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldPlateRegion, v))
}

// PlateUploadNumEQ applies the EQ predicate on the "plate_upload_num" field.
func PlateUploadNumEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldPlateUploadNum, v))
}

// PlateUploadNumNEQ applies the NEQ predicate on the "plate_upload_num" field.
func PlateUploadNumNEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldPlateUploadNum, v))
}

// PlateUploadNumIn applies the In predicate on the "plate_upload_num" field.
func PlateUploadNumIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldPlateUploadNum, vs...))
}

// PlateUploadNumNotIn applies the NotIn predicate on the "plate_upload_num" field.
func PlateUploadNumNotIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldPlateUploadNum, vs...))
}

// PlateUploadNumGT applies the GT predicate on the "plate_upload_num" field.
func PlateUploadNumGT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldPlateUploadNum, v))
}

// PlateUploadNumGTE applies the GTE predicate on the "plate_upload_num" field.
func PlateUploadNumGTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldPlateUploadNum, v))
}

// PlateUploadNumLT applies the LT predicate on the "plate_upload_num" field.
func PlateUploadNumLT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldPlateUploadNum, v))
}

// PlateUploadNumLTE applies the LTE predicate on the "plate_upload_num" field.
func PlateUploadNumLTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldPlateUploadNum, v))
}

// PlateUploadNumIsNil applies the IsNil predicate on the "plate_upload_num" field.
func PlateUploadNumIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldPlateUploadNum))
}

// PlateUploadNumNotNil applies the NotNil predicate on the "plate_upload_num" field.
func PlateUploadNumNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldPlateUploadNum))
}

// SnapAllowUserEQ applies the EQ predicate on the "snap_allow_user" field.
func SnapAllowUserEQ(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapAllowUser, v))
}

// SnapAllowUserNEQ applies the NEQ predicate on the "snap_allow_user" field.
func SnapAllowUserNEQ(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldSnapAllowUser, v))
}

// SnapAllowUserIsNil applies the IsNil predicate on the "snap_allow_user" field.
func SnapAllowUserIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldSnapAllowUser))
}

// SnapAllowUserNotNil applies the NotNil predicate on the "snap_allow_user" field.
func SnapAllowUserNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldSnapAllowUser))
}

// SnapAllowUserEndTimeEQ applies the EQ predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeNEQ applies the NEQ predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeIn applies the In predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldSnapAllowUserEndTime, vs...))
}

// SnapAllowUserEndTimeNotIn applies the NotIn predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldSnapAllowUserEndTime, vs...))
}

// SnapAllowUserEndTimeGT applies the GT predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeGTE applies the GTE predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeLT applies the LT predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeLTE applies the LTE predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeContains applies the Contains predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeHasPrefix applies the HasPrefix predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeHasSuffix applies the HasSuffix predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeIsNil applies the IsNil predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldSnapAllowUserEndTime))
}

// SnapAllowUserEndTimeNotNil applies the NotNil predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldSnapAllowUserEndTime))
}

// SnapAllowUserEndTimeEqualFold applies the EqualFold predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldSnapAllowUserEndTime, v))
}

// SnapAllowUserEndTimeContainsFold applies the ContainsFold predicate on the "snap_allow_user_end_time" field.
func SnapAllowUserEndTimeContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldSnapAllowUserEndTime, v))
}

// SnapDefenceCodeEQ applies the EQ predicate on the "snap_defence_code" field.
func SnapDefenceCodeEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeNEQ applies the NEQ predicate on the "snap_defence_code" field.
func SnapDefenceCodeNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeIn applies the In predicate on the "snap_defence_code" field.
func SnapDefenceCodeIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldSnapDefenceCode, vs...))
}

// SnapDefenceCodeNotIn applies the NotIn predicate on the "snap_defence_code" field.
func SnapDefenceCodeNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldSnapDefenceCode, vs...))
}

// SnapDefenceCodeGT applies the GT predicate on the "snap_defence_code" field.
func SnapDefenceCodeGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeGTE applies the GTE predicate on the "snap_defence_code" field.
func SnapDefenceCodeGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeLT applies the LT predicate on the "snap_defence_code" field.
func SnapDefenceCodeLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeLTE applies the LTE predicate on the "snap_defence_code" field.
func SnapDefenceCodeLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeContains applies the Contains predicate on the "snap_defence_code" field.
func SnapDefenceCodeContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeHasPrefix applies the HasPrefix predicate on the "snap_defence_code" field.
func SnapDefenceCodeHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeHasSuffix applies the HasSuffix predicate on the "snap_defence_code" field.
func SnapDefenceCodeHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeIsNil applies the IsNil predicate on the "snap_defence_code" field.
func SnapDefenceCodeIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldSnapDefenceCode))
}

// SnapDefenceCodeNotNil applies the NotNil predicate on the "snap_defence_code" field.
func SnapDefenceCodeNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldSnapDefenceCode))
}

// SnapDefenceCodeEqualFold applies the EqualFold predicate on the "snap_defence_code" field.
func SnapDefenceCodeEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldSnapDefenceCode, v))
}

// SnapDefenceCodeContainsFold applies the ContainsFold predicate on the "snap_defence_code" field.
func SnapDefenceCodeContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldSnapDefenceCode, v))
}

// SnapDeviceIDEQ applies the EQ predicate on the "snap_device_id" field.
func SnapDeviceIDEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapDeviceID, v))
}

// SnapDeviceIDNEQ applies the NEQ predicate on the "snap_device_id" field.
func SnapDeviceIDNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldSnapDeviceID, v))
}

// SnapDeviceIDIn applies the In predicate on the "snap_device_id" field.
func SnapDeviceIDIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldSnapDeviceID, vs...))
}

// SnapDeviceIDNotIn applies the NotIn predicate on the "snap_device_id" field.
func SnapDeviceIDNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldSnapDeviceID, vs...))
}

// SnapDeviceIDGT applies the GT predicate on the "snap_device_id" field.
func SnapDeviceIDGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldSnapDeviceID, v))
}

// SnapDeviceIDGTE applies the GTE predicate on the "snap_device_id" field.
func SnapDeviceIDGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldSnapDeviceID, v))
}

// SnapDeviceIDLT applies the LT predicate on the "snap_device_id" field.
func SnapDeviceIDLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldSnapDeviceID, v))
}

// SnapDeviceIDLTE applies the LTE predicate on the "snap_device_id" field.
func SnapDeviceIDLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldSnapDeviceID, v))
}

// SnapDeviceIDContains applies the Contains predicate on the "snap_device_id" field.
func SnapDeviceIDContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldSnapDeviceID, v))
}

// SnapDeviceIDHasPrefix applies the HasPrefix predicate on the "snap_device_id" field.
func SnapDeviceIDHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldSnapDeviceID, v))
}

// SnapDeviceIDHasSuffix applies the HasSuffix predicate on the "snap_device_id" field.
func SnapDeviceIDHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldSnapDeviceID, v))
}

// SnapDeviceIDIsNil applies the IsNil predicate on the "snap_device_id" field.
func SnapDeviceIDIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldSnapDeviceID))
}

// SnapDeviceIDNotNil applies the NotNil predicate on the "snap_device_id" field.
func SnapDeviceIDNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldSnapDeviceID))
}

// SnapDeviceIDEqualFold applies the EqualFold predicate on the "snap_device_id" field.
func SnapDeviceIDEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldSnapDeviceID, v))
}

// SnapDeviceIDContainsFold applies the ContainsFold predicate on the "snap_device_id" field.
func SnapDeviceIDContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldSnapDeviceID, v))
}

// SnapInCarPeopleNumEQ applies the EQ predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapInCarPeopleNum, v))
}

// SnapInCarPeopleNumNEQ applies the NEQ predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumNEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldSnapInCarPeopleNum, v))
}

// SnapInCarPeopleNumIn applies the In predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldSnapInCarPeopleNum, vs...))
}

// SnapInCarPeopleNumNotIn applies the NotIn predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumNotIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldSnapInCarPeopleNum, vs...))
}

// SnapInCarPeopleNumGT applies the GT predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumGT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldSnapInCarPeopleNum, v))
}

// SnapInCarPeopleNumGTE applies the GTE predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumGTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldSnapInCarPeopleNum, v))
}

// SnapInCarPeopleNumLT applies the LT predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumLT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldSnapInCarPeopleNum, v))
}

// SnapInCarPeopleNumLTE applies the LTE predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumLTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldSnapInCarPeopleNum, v))
}

// SnapInCarPeopleNumIsNil applies the IsNil predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldSnapInCarPeopleNum))
}

// SnapInCarPeopleNumNotNil applies the NotNil predicate on the "snap_in_car_people_num" field.
func SnapInCarPeopleNumNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldSnapInCarPeopleNum))
}

// SnapLanNoEQ applies the EQ predicate on the "snap_lan_no" field.
func SnapLanNoEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapLanNo, v))
}

// SnapLanNoNEQ applies the NEQ predicate on the "snap_lan_no" field.
func SnapLanNoNEQ(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldSnapLanNo, v))
}

// SnapLanNoIn applies the In predicate on the "snap_lan_no" field.
func SnapLanNoIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldSnapLanNo, vs...))
}

// SnapLanNoNotIn applies the NotIn predicate on the "snap_lan_no" field.
func SnapLanNoNotIn(vs ...int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldSnapLanNo, vs...))
}

// SnapLanNoGT applies the GT predicate on the "snap_lan_no" field.
func SnapLanNoGT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldSnapLanNo, v))
}

// SnapLanNoGTE applies the GTE predicate on the "snap_lan_no" field.
func SnapLanNoGTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldSnapLanNo, v))
}

// SnapLanNoLT applies the LT predicate on the "snap_lan_no" field.
func SnapLanNoLT(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldSnapLanNo, v))
}

// SnapLanNoLTE applies the LTE predicate on the "snap_lan_no" field.
func SnapLanNoLTE(v int) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldSnapLanNo, v))
}

// SnapLanNoIsNil applies the IsNil predicate on the "snap_lan_no" field.
func SnapLanNoIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldSnapLanNo))
}

// SnapLanNoNotNil applies the NotNil predicate on the "snap_lan_no" field.
func SnapLanNoNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldSnapLanNo))
}

// SnapOpenStrobeEQ applies the EQ predicate on the "snap_open_strobe" field.
func SnapOpenStrobeEQ(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldSnapOpenStrobe, v))
}

// SnapOpenStrobeNEQ applies the NEQ predicate on the "snap_open_strobe" field.
func SnapOpenStrobeNEQ(v bool) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldSnapOpenStrobe, v))
}

// SnapOpenStrobeIsNil applies the IsNil predicate on the "snap_open_strobe" field.
func SnapOpenStrobeIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldSnapOpenStrobe))
}

// SnapOpenStrobeNotNil applies the NotNil predicate on the "snap_open_strobe" field.
func SnapOpenStrobeNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldSnapOpenStrobe))
}

// VehicleBoundingBoxIsNil applies the IsNil predicate on the "vehicle_bounding_box" field.
func VehicleBoundingBoxIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldVehicleBoundingBox))
}

// VehicleBoundingBoxNotNil applies the NotNil predicate on the "vehicle_bounding_box" field.
func VehicleBoundingBoxNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldVehicleBoundingBox))
}

// VehicleSeriesEQ applies the EQ predicate on the "vehicle_series" field.
func VehicleSeriesEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEQ(FieldVehicleSeries, v))
}

// VehicleSeriesNEQ applies the NEQ predicate on the "vehicle_series" field.
func VehicleSeriesNEQ(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNEQ(FieldVehicleSeries, v))
}

// VehicleSeriesIn applies the In predicate on the "vehicle_series" field.
func VehicleSeriesIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIn(FieldVehicleSeries, vs...))
}

// VehicleSeriesNotIn applies the NotIn predicate on the "vehicle_series" field.
func VehicleSeriesNotIn(vs ...string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotIn(FieldVehicleSeries, vs...))
}

// VehicleSeriesGT applies the GT predicate on the "vehicle_series" field.
func VehicleSeriesGT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGT(FieldVehicleSeries, v))
}

// VehicleSeriesGTE applies the GTE predicate on the "vehicle_series" field.
func VehicleSeriesGTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldGTE(FieldVehicleSeries, v))
}

// VehicleSeriesLT applies the LT predicate on the "vehicle_series" field.
func VehicleSeriesLT(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLT(FieldVehicleSeries, v))
}

// VehicleSeriesLTE applies the LTE predicate on the "vehicle_series" field.
func VehicleSeriesLTE(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldLTE(FieldVehicleSeries, v))
}

// VehicleSeriesContains applies the Contains predicate on the "vehicle_series" field.
func VehicleSeriesContains(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContains(FieldVehicleSeries, v))
}

// VehicleSeriesHasPrefix applies the HasPrefix predicate on the "vehicle_series" field.
func VehicleSeriesHasPrefix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasPrefix(FieldVehicleSeries, v))
}

// VehicleSeriesHasSuffix applies the HasSuffix predicate on the "vehicle_series" field.
func VehicleSeriesHasSuffix(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldHasSuffix(FieldVehicleSeries, v))
}

// VehicleSeriesIsNil applies the IsNil predicate on the "vehicle_series" field.
func VehicleSeriesIsNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldIsNull(FieldVehicleSeries))
}

// VehicleSeriesNotNil applies the NotNil predicate on the "vehicle_series" field.
func VehicleSeriesNotNil() predicate.VehicleData {
	return predicate.VehicleData(sql.FieldNotNull(FieldVehicleSeries))
}

// VehicleSeriesEqualFold applies the EqualFold predicate on the "vehicle_series" field.
func VehicleSeriesEqualFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldEqualFold(FieldVehicleSeries, v))
}

// VehicleSeriesContainsFold applies the ContainsFold predicate on the "vehicle_series" field.
func VehicleSeriesContainsFold(v string) predicate.VehicleData {
	return predicate.VehicleData(sql.FieldContainsFold(FieldVehicleSeries, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VehicleData) predicate.VehicleData {
	return predicate.VehicleData(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VehicleData) predicate.VehicleData {
	return predicate.VehicleData(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VehicleData) predicate.VehicleData {
	return predicate.VehicleData(sql.NotPredicates(p))
}
